"""Compatibility exports for widget-related styles."""

from .button_styles import (
    BUTTON_STYLE,
    ENV_BUTTON_STYLE,
    ENV_CANCEL_BUTTON_STYLE,
    ENV_SAVE_BUTTON_STYLE,
    RESTORE_BUTTON_STYLE,
)
from .database_styles import DB_DIALOG_STYLE, TABLE_WIDGET_STYLE, TAB_WIDGET_STYLE
from .env_styles import (
    ENV_DIALOG_STYLE,
    ENV_GROUPBOX_STYLE,
    ENV_LINE_EDIT_STYLE,
    ENV_RADIO_BUTTON_STYLE,
    ENV_STATUS_LABEL_STYLE,
)

__all__ = [
    "BUTTON_STYLE",
    "DB_DIALOG_STYLE",
    "ENV_BUTTON_STYLE",
    "ENV_CANCEL_BUTTON_STYLE",
    "ENV_DIALOG_STYLE",
    "ENV_GROUPBOX_STYLE",
    "ENV_LINE_EDIT_STYLE",
    "ENV_RADIO_BUTTON_STYLE",
    "ENV_SAVE_BUTTON_STYLE",
    "ENV_STATUS_LABEL_STYLE",
    "RESTORE_BUTTON_STYLE",
    "TABLE_WIDGET_STYLE",
    "TAB_WIDGET_STYLE",
]
